# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisPolyAlf.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalysisPolyAlf(object):
    def setupUi(self, AnalysisPolyAlf):
        AnalysisPolyAlf.setObjectName("AnalysisPolyAlf")
        AnalysisPolyAlf.resize(600, 700)
        AnalysisPolyAlf.setMinimumSize(QtCore.QSize(600, 700))
        AnalysisPolyAlf.setMaximumSize(QtCore.QSize(600, 700))
        self.centralwidget = QtWidgets.QWidget(AnalysisPolyAlf)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 36, 221, 31))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 80, 401, 141))
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(450, 10, 101, 191))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 210, 121, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 470, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 500, 221, 31))
        self.label_6.setObjectName("label_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 540, 301, 111))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(370, 500, 201, 151))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 51, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 40, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 500, 21, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 500, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 270, 261, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 270, 91, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 270, 21, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_5.setGeometry(QtCore.QRect(450, 270, 101, 191))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(1)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 310, 141, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_6.setGeometry(QtCore.QRect(280, 340, 61, 91))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 440, 141, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        AnalysisPolyAlf.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnalysisPolyAlf)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        AnalysisPolyAlf.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnalysisPolyAlf)
        self.statusbar.setObjectName("statusbar")
        AnalysisPolyAlf.setStatusBar(self.statusbar)

        self.retranslateUi(AnalysisPolyAlf)
        QtCore.QMetaObject.connectSlotsByName(AnalysisPolyAlf)

    def retranslateUi(self, AnalysisPolyAlf):
        _translate = QtCore.QCoreApplication.translate
        AnalysisPolyAlf.setWindowTitle(_translate("AnalysisPolyAlf", "Analysis"))
        self.label.setText(_translate("AnalysisPolyAlf", "Метод индекса совпадений:"))
        self.label_2.setText(_translate("AnalysisPolyAlf", "Учет начинается с                   ИС"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Строка"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AnalysisPolyAlf", "ИС"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AnalysisPolyAlf", "ВИС"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AnalysisPolyAlf", "Сдвиг"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Варианты ключа"))
        self.pushButton.setText(_translate("AnalysisPolyAlf", "Вывести варианты"))
        self.label_4.setText(_translate("AnalysisPolyAlf", "Автокорреляционный метод:"))
        self.label_5.setText(_translate("AnalysisPolyAlf", "Метод Касиски:"))
        self.label_6.setText(_translate("AnalysisPolyAlf", "Длина окна для поиска повторений:"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Повторения"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("AnalysisPolyAlf", "Количество"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("AnalysisPolyAlf", "Индексы"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Длина ключа"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("AnalysisPolyAlf", "Вероятность "))
        self.lineEdit.setText(_translate("AnalysisPolyAlf", "0.04"))
        self.pushButton_2.setText(_translate("AnalysisPolyAlf", "Рассчитать"))
        self.lineEdit_2.setText(_translate("AnalysisPolyAlf", "3"))
        self.pushButton_3.setText(_translate("AnalysisPolyAlf", "Рассчитать"))
        self.label_3.setText(_translate("AnalysisPolyAlf", "Длина ключа: "))
        self.lineEdit_3.setText(_translate("AnalysisPolyAlf", "3"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Варианты ключа"))
        self.pushButton_4.setText(_translate("AnalysisPolyAlf", "Рассчитать смещения"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("AnalysisPolyAlf", "Сдвиг"))
        self.pushButton_5.setText(_translate("AnalysisPolyAlf", "Вывести варианты"))
